/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.dlect.ui.prefs.subject;

import com.google.common.base.Joiner;
import com.google.common.collect.HashBasedTable;
import com.google.common.collect.ImmutableSortedSet;
import com.google.common.collect.Maps;
import com.google.common.collect.Table;
import java.awt.Color;
import java.awt.Font;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.beans.PropertyChangeEvent;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.SortedSet;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.SwingConstants;
import javax.swing.border.Border;
import javax.swing.border.CompoundBorder;
import javax.swing.border.EmptyBorder;
import javax.swing.border.MatteBorder;
import org.dlect.controller.MainController;
import org.dlect.events.Event;
import org.dlect.events.EventListener;
import org.dlect.events.wrapper.Wrappers;
import org.dlect.helper.LectureHelper;
import org.dlect.helpers.StringUtil;
import org.dlect.model.Lecture;
import org.dlect.model.LectureDownload;
import org.dlect.model.Stream;
import org.dlect.model.Subject;
import org.dlect.model.formatter.DownloadType;
import org.dlect.ui.helper.WrappingUtil;

/**
 *
 * @author lee
 */
public class AdvancedLecturePanel extends SubjectPreferencesPanel implements EventListener {

    private final Subject s;
    private final MainController c;
    private JLabel jLabel1;
    private final Map<DownloadType, JLabel> tableHeadings = Maps.newEnumMap(DownloadType.class);
    private final Table<Lecture, DownloadType, DownloadInputs> checkBoxMapping = HashBasedTable.create();
    private final String dateFormat = "yyyy/MM/dd HH:mm";
    private Font boldFont, standardFont;

    /**
     * Creates new form AdvancedLecturePanel
     * @param s
     * @param c
     */
    public AdvancedLecturePanel(Subject s, MainController c) {
        super(s, c);
        this.s = s;
        this.c = c;
        initComponents();
        initSubjectLectures();
        Wrappers.addSwingListenerTo(this, c, Subject.class, Lecture.class, Stream.class, LectureDownload.class);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {
        jLabel1 = new javax.swing.JLabel();
        final Font labelFont = jLabel1.getFont().deriveFont(jLabel1.getFont().getSize() + 2f);

        jLabel1.setFont(labelFont);
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Lecture");
        jLabel1.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 1, Color.BLACK));

        for (DownloadType downloadType : DownloadType.values()) {
            JLabel label = new JLabel(downloadType.toString());
            label.setFont(labelFont);
            label.setHorizontalAlignment(SwingConstants.CENTER);
            label.setBorder(BorderFactory.createMatteBorder(0, 1, 1, 1, Color.BLACK));

            tableHeadings.put(downloadType, label);
        }
        setLayout(new GridBagLayout());
        addComponents();
    }

    private void addComponents() {
        GridBagConstraints gridBagConstraints;
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        add(jLabel1, gridBagConstraints);
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.weightx = 0;
        for (JLabel label : tableHeadings.values()) {
            add(label, gridBagConstraints);
            gridBagConstraints.gridx += 2;
        }
    }

    private void initSubjectLectures() {
        SortedSet<Lecture> lectures = s.getLectures();
        GridBagConstraints gbc = new GridBagConstraints();
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.BOTH;
        standardFont = this.getFont();
        boldFont = standardFont.deriveFont(Font.BOLD);
        Border labelBorder = new CompoundBorder(new MatteBorder(0, 0, 1, 1, Color.BLACK), new EmptyBorder(0, 1, 1, 2));
        for (Lecture l : lectures) {
            String name = StringUtil.formatDate(dateFormat, l.getTime()) + formatStreams(" [", l, "]");
            JLabel la = new JLabel(name);
            JPanel lp = WrappingUtil.wrapCenterBothFill(la, labelBorder);
            gbc.gridx = 0;
            gbc.weightx = 1.;
            this.add(lp, gbc);
            for (DownloadType dt : DownloadType.values()) {
                addDownloadType(l, dt, gbc);
            }
            gbc.gridy++;
        }
    }

    private static String formatStreams(String prefix, Lecture l, String postfix) {
        ImmutableSortedSet<Stream> s = l.getStreams();
        List<String> str = new ArrayList<>();
        for (Stream stream : s) {
            str.add(stream.getName());
        }
        if (str.isEmpty()) {
            return "";
        }
        StringBuilder b = new StringBuilder(prefix);
        b.append(Joiner.on(", ").skipNulls().join(str));
        return b.append(postfix).toString();
    }

    private void addDownloadType(Lecture l, DownloadType dt, GridBagConstraints gbc) {
        Border checkBorder = new MatteBorder(0, 1, 1, 0, Color.BLACK);
        Border buttonBorder = new MatteBorder(0, 1, 1, 1, Color.BLACK);
        LectureDownload ld = l.getLectureDownloads().get(dt);
        if (ld == null) {
            // TODO error.
            ld = new LectureDownload(null, null, false, false);
        }
        boolean dling = LectureHelper.isLectureDownloadEnabled(l, ld);
        boolean dled = ld.isDownloaded();
        JCheckBox enabledCheck = new JCheckBox();
        enabledCheck.setEnabled(!dled);
        enabledCheck.setSelected(dling);

        gbc.gridx++;
        gbc.weightx = 0;
        this.add(WrappingUtil.wrapCenterNoFill(enabledCheck, checkBorder), gbc);

        JButton dlButton = new JButton(dled ? "Downloaded" : "Download");
        dlButton.setEnabled(!dled);

        gbc.gridx++;
        this.add(WrappingUtil.wrapCenterNoFill(dlButton, buttonBorder), gbc);

        DownloadInputs p = new DownloadInputs(enabledCheck, dlButton);
        checkBoxMapping.put(l, dt, p);

        //DownloadActionListener a = DownloadActionListener.create(s, l, dt, c, this);
        //enabledCheck.addActionListener(a);
        //dlButton.addActionListener(a);
        
        // TODO Add listeners to download button and enabled checkbox.
    }

    public void downloadStarting(Subject s, Lecture l, DownloadType t) {
        if (s.equals(this.s)) {
            DownloadInputs pair = checkBoxMapping.get(l, t);
            pair.getLeft().setEnabled(false);
            pair.getLeft().setSelected(true);
            pair.getRight().setEnabled(false);
            pair.getRight().setText("Downloading");
            pair.getRight().setFont(boldFont);
        }
    }

    public void downloadCompleted(Subject s, Lecture l, DownloadType t) {
        if (s.equals(this.s)) {
            boolean dled = false;//l.isFilePresent(t);
            DownloadInputs pair = checkBoxMapping.get(l, t);
            pair.getLeft().setEnabled(!dled);
            pair.getLeft().setSelected(dled);
            pair.getRight().setEnabled(!dled);
            pair.getRight().setText(dled ? "Downloaded" : "Download");
            pair.getRight().setFont(standardFont);
        }
    }

    public void propertyChange(PropertyChangeEvent evt) {
        // TODO
//        DownloadActionListener d = (DownloadActionListener) evt.getSource();
//        DownloadInputs inputs = checkBoxMapping.get(d.getL(), d.getDt());
//        inputs.getLeft().setSelected(isEnabled(d.getL(), d.getDt()));
    }

    @Override
    public void processEvent(Event e) {
        // TODO
    }

    @Override
    public void doPreShow() {
        // TODO write
    }

    @Override
    public String getTabName() {
        return "Lectures";
    }

    @Override
    public String getTabTooltip() {
        return "Download individual lectures";
    }

    private static final class DownloadInputs {

        private final JCheckBox left;
        private final JButton right;

        public DownloadInputs(JCheckBox left, JButton right) {
            this.left = left;
            this.right = right;
        }

        public JCheckBox getLeft() {
            return left;
        }

        public JButton getRight() {
            return right;
        }

    }
}
