package org.lee.echo360.ui;

import org.lee.echo360.control.ControllerAction;
import org.lee.echo360.control.ControllerListener;
import org.lee.echo360.control.controllers.DownloadProgressListener;
import org.lee.echo360.control.controllers.MainController;
import org.lee.echo360.model.ActionResult;
import org.lee.echo360.model.DownloadType;
import org.lee.echo360.model.Lecture;
import org.lee.echo360.model.Subject;
import org.lee.echo360.ui.layout.AnimatedHideLayoutManager;

/**
 *
 * @author lee
 */
public class CoursePane extends javax.swing.JLayeredPane implements
        ControllerListener, DownloadProgressListener {

    private Subject course;
    private final AnimatedHideLayoutManager lm;
    private final MainController controller;

    /**
     * Creates new form CoursePane
     */
    public CoursePane(MainController controller) {
        this.controller = controller;
        initComponents();
        lm = new AnimatedHideLayoutManager(courseHeader1, courseDetailPanel1, this);
        this.setLayout(lm);
    }

    public void animateDown() {
        lm.animateDown();
    }

    public void animateUp() {
        lm.animateUp();
    }

    public void animateToggle() {
        lm.animateToggle();
    }

    public void setSubject(Subject c) {
        this.course = c;
        courseDetailPanel1.setSubject(course);
        courseHeader1.setSubject(course);
    }

    public void refresh() {
        courseHeader1.refresh();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        courseHeader1 = new CourseHeader(controller);
        courseDetailPanel1 = new CourseDetailPanel(controller);

        courseHeader1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                courseHeader1MouseClicked(evt);
            }
        });
        courseHeader1.setBounds(0, 0, 38, 28);
        add(courseHeader1, new Integer(2));
        courseDetailPanel1.setBounds(0, 0, 296, 87);
        add(courseDetailPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
    }// </editor-fold>

    private void courseHeader1MouseClicked(java.awt.event.MouseEvent evt) {
        lm.animateToggle();
    }
    // Variables declaration - do not modify
    private org.lee.echo360.ui.CourseDetailPanel courseDetailPanel1;
    private org.lee.echo360.ui.CourseHeader courseHeader1;
    // End of variables declaration

    @Override
    public void start(ControllerAction action) {
        //    throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void finished(ControllerAction action, ActionResult ar) {
        // throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void error(Throwable thrwbl) {
//        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void downloadingStarted(Subject subject) {
        //      throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void downloadingFinished(Subject subject) {
        //    throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void downloadStarting(Subject s, Lecture l, DownloadType t) {
        //  throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void downloadCompleted(Subject s, Lecture l, DownloadType t) {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
