/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.dlect.events.listenable;

import javax.annotation.Nullable;
import org.dlect.events.EventAdapter;
import org.dlect.events.EventID;
import org.dlect.events.collections.CollectionEventHelper;

public class ListenableCollectionEventHelper<T extends Listenable<T>> extends CollectionEventHelper<T> {

    /**
     * Creates a new collection event helper that configures objects passing through to have their parent adapters to be
     * the adapter given to this method.
     *
     * @param source  The source of the events that are generated by this helper.
     * @param eventID The event ID to use in the events generated by this helper.
     * @param adapter The adapter to fire events to and to configure added objects to have as their parent.
     */
    public ListenableCollectionEventHelper(Object source, EventID eventID, EventAdapter adapter) {
        super(source, eventID, adapter);
    }

    /**
     * Sets the given object's parent adapter to
     *
     * @param elm
     * @param parent
     */
    protected static void addListenable(@Nullable Listenable<?> elm, EventAdapter parent) {
        if (elm == null) {
            return;
        }
        EventAdapter elmAdapt = elm.getAdapter();
        if (elmAdapt == null) {
            throw new IllegalStateException(debugNullAdapter(elm));
        }
        EventAdapter elmParentAdapt = elmAdapt.getParentAdapter();

        if (elmParentAdapt == null) {
            elmAdapt.setParentAdapter(parent);
        } else {
            throw new IllegalStateException(debugElmAndParent(elm, elmParentAdapt) + " is not null. This means that "
                                            + "another object has configured the element.");
        }
    }

    private static String debugElmAndParent(Listenable<?> elm, EventAdapter elmParentAdapt) {
        return "Trying to add an element(" + elm + ") whose parent adapter(" + elmParentAdapt + ")";
    }

    private static String debugNullAdapter(Listenable<?> elm) {
        return "Element " + elm + " has a null event adapter.";
    }

    protected static void removeListenable(@Nullable Listenable<?> elm, EventAdapter parent) {
        if (elm == null) {
            return;
        }
        EventAdapter elmAdapt = elm.getAdapter();
        if (elmAdapt == null) {
            throw new IllegalStateException(debugNullAdapter(elm));
        }
        EventAdapter elmParentAdapt = elmAdapt.getParentAdapter();

        if (elmParentAdapt == parent) {
            elmAdapt.setParentAdapter(null);
        } else {
            throw new IllegalStateException(debugElmAndParent(elm, elmParentAdapt) + " is different from the adapter(" + parent
                                            + ") it should have been.");
        }
    }

    @Override
    public void fireAdd(T addedElement) {
        addListenable(addedElement, this.getAdapter());
        super.fireAdd(addedElement);
    }

    @Override
    public void fireRemove(T removedElement) {
        removeListenable(removedElement, this.getAdapter());
        super.fireRemove(removedElement);
    }

    @Override
    public void fireReplace(T original, T replacement) {
        addListenable(replacement, this.getAdapter());
        removeListenable(original, this.getAdapter());
        super.fireReplace(original, replacement);
    }

}
